apiVersion: v1
kind: Secret
metadata:
  name: postgres-root-credentials
  namespace: default
type: Opaque
stringData:
  connection-string: "postgres://postgres:rootpassword@postgres-service:5432/postgres?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-provisioner-db-credentials
  namespace: default
type: Opaque
stringData:
  databases: |
    [
      {
        "database": "app_db",
        "user": "app_user",
        "password": "securepassword123"
      },
      {
        "database": "analytics_db",
        "user": "analytics_user",
        "password": "analyticspass456"
      }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-provisioner-config
  namespace: default
data:
  config.json: |
    {
      "root_connection_string": "${ROOT_CONNECTION_STRING}",
      "databases": ${DATABASES_JSON}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-provisioner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-provisioner
  template:
    metadata:
      labels:
        app: pg-provisioner
    spec:
      initContainers:
      - name: config-interpolator
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          cat /config-template/config.json | \
          sed "s|\${ROOT_CONNECTION_STRING}|$(cat /secrets/root/connection-string)|g" | \
          sed "s|\${DATABASES_JSON}|$(cat /secrets/databases/databases)|g" > /config-output/config.json
        volumeMounts:
        - name: config-template
          mountPath: /config-template
        - name: config-output
          mountPath: /config-output
        - name: root-secret
          mountPath: /secrets/root
        - name: databases-secret
          mountPath: /secrets/databases
      containers:
      - name: provisioner
        image: pg-provisioner:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_PATH
          value: /config/config.json
        - name: WATCH_MODE
          value: "true"
        volumeMounts:
        - name: config-output
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-template
        configMap:
          name: pg-provisioner-config
      - name: config-output
        emptyDir: {}
      - name: root-secret
        secret:
          secretName: postgres-root-credentials
      - name: databases-secret
        secret:
          secretName: pg-provisioner-db-credentials
      restartPolicy: Always
